[SERVICE]
    Flush        1
    Log_Level    info
    Parsers_File parsers.conf

[INPUT]
    Name   tail
    Path   /var/log/*.log
    Tag    meridian.host

[INPUT]
    Name   tail
    Path   /var/log/system.log
    Tag    meridian.system

[INPUT]
    Name            systemd
    Tag             meridian.journal
    Systemd_Filter  _SYSTEMD_UNIT=docker.service
    Read_From_Tail  On


[OUTPUT]
    Name          forward
    Match         *
    Host          vector
    Port          24224
    tls           on
    tls.ca_file   /certs/rootCA.pem
    tls.crt_file  /certs/meridian.local.pem
    tls.key_file  /certs/meridian.local-key.pem
